### ISSUE TITLE
Dispatch should be memoized via useCallback

### ISSUE THREAD

**Issue by jgolieb** [pret-a-porter/use-enhanced-reducer#1]
I tried using this library to apply a middleware that performs API calls via `useEffect`. When calling `dispatch` from `useEffect`, the best practice per the [React docs](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies) (which is also enforced by create-react-app's ESLint rules) is to include `dispatch` in the dependency array passed to `useEffect`. However, this created an infinite loop. The original [`useReducer`](https://reactjs.org/docs/hooks-reference.html#usereducer) avoids this problem by guaranteeing that dispatch function identity is stable and won’t change on re-renders. By returning `useCallback(enhancedDispatch)` rather than just the bare `enhancedDispatch` function, I believe you would avoid this problem. I tried it in my own code and it seems to be working.

**Comment by pret-a-porter** [comment]
Could you make pull request with fix?

**Comment by Dobby89** [comment]
@jgolieb Please can you provide an example of the change needed?
